--星际战舰 质量加速器
local m=14801749
local cm=_G["c"..m]
function cm.initial_effect(c)
    c:EnableCounterPermit(0x48f)
    --Activate
    local e0=Effect.CreateEffect(c)
    e0:SetCategory(CATEGORY_COUNTER)
    e0:SetType(EFFECT_TYPE_ACTIVATE)
    e0:SetCode(EVENT_FREE_CHAIN)
    e0:SetTarget(cm.target)
    e0:SetOperation(cm.activate)
    c:RegisterEffect(e0)
    --to hand
    local e1=Effect.CreateEffect(c)
    e1:SetDescription(aux.Stringid(m,0))
    e1:SetCategory(CATEGORY_DRAW)
    e1:SetType(EFFECT_TYPE_IGNITION)
    e1:SetRange(LOCATION_FZONE)
    e1:SetCountLimit(1,m)
    e1:SetLabel(3)
    e1:SetCost(cm.cost)
    e1:SetTarget(cm.drtg)
    e1:SetOperation(cm.drop)
    c:RegisterEffect(e1)
    --spsummon (mythical)
    local e2=e1:Clone()
    e2:SetDescription(aux.Stringid(m,1))
    e2:SetCountLimit(1,m)
    e2:SetLabel(6)
    e2:SetTarget(cm.drtg1)
    e2:SetOperation(cm.drop1)
    c:RegisterEffect(e2)
    --spsummon (generic)
    local e3=e2:Clone()
    e3:SetDescription(aux.Stringid(m,2))
    e3:SetCountLimit(1,m)
    e3:SetLabel(9)
    e3:SetTarget(cm.drtg2)
    e3:SetOperation(cm.drop2)
    c:RegisterEffect(e3)
    --spsummon (generic)
    local e4=e3:Clone()
    e4:SetDescription(aux.Stringid(m,3))
    e4:SetCountLimit(1,m)
    e4:SetLabel(12)
    e4:SetTarget(cm.drtg3)
    e4:SetOperation(cm.drop3)
    c:RegisterEffect(e4)
    --Pos Change
    local e6=Effect.CreateEffect(c)
    e6:SetType(EFFECT_TYPE_FIELD)
    e6:SetCode(EFFECT_SET_POSITION)
    e6:SetRange(LOCATION_FZONE)
    e6:SetTarget(cm.target2)
    e6:SetTargetRange(LOCATION_MZONE,0)
    e6:SetValue(POS_FACEUP_DEFENSE)
    c:RegisterEffect(e6)
    --
    local e7=Effect.CreateEffect(c)
    e7:SetType(EFFECT_TYPE_FIELD)
    e7:SetCode(EFFECT_DEFENSE_ATTACK)
    e7:SetRange(LOCATION_FZONE)
    e7:SetTargetRange(LOCATION_MZONE,0)
    e7:SetTarget(cm.target2)
    e7:SetValue(1)
    c:RegisterEffect(e7)
end
function cm.target2(e,c)
    return c:IsSetCard(0x480b) and c:IsFaceup()
end
function cm.target(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return Duel.IsCanAddCounter(tp,0x48f,3,e:GetHandler()) end
    Duel.SetOperationInfo(0,CATEGORY_COUNTER,nil,3,0,0x48f)
end
function cm.activate(e,tp,eg,ep,ev,re,r,rp)
    local c=e:GetHandler()
    if c:IsRelateToEffect(e) then
        c:AddCounter(0x48f,3)
    end
end
function cm.cost(e,tp,eg,ep,ev,re,r,rp,chk)
    local ct=e:GetLabel()
    if chk==0 then return Duel.IsCanRemoveCounter(tp,1,0,0x48f,ct,REASON_COST) end
    Duel.Hint(HINT_OPSELECTED,1-tp,e:GetDescription())
    Duel.RemoveCounter(tp,1,0,0x48f,ct,REASON_COST)
end
function cm.drtg(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return Duel.IsPlayerCanDraw(tp,1) end
    Duel.SetTargetPlayer(tp)
    Duel.SetTargetParam(1)
    Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,tp,1)
end
function cm.drop(e,tp,eg,ep,ev,re,r,rp)
    local p,d=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER,CHAININFO_TARGET_PARAM)
    Duel.Draw(p,d,REASON_EFFECT)
end
function cm.drtg1(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return Duel.IsPlayerCanDraw(tp,2) end
    Duel.SetTargetPlayer(tp)
    Duel.SetTargetParam(2)
    Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,tp,2)
end
function cm.drop1(e,tp,eg,ep,ev,re,r,rp)
    local p,d=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER,CHAININFO_TARGET_PARAM)
    Duel.Draw(p,d,REASON_EFFECT)
    local e1=Effect.CreateEffect(e:GetHandler())
    e1:SetType(EFFECT_TYPE_FIELD)
    e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_OATH)
    e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
    e1:SetReset(RESET_PHASE+PHASE_END)
    e1:SetTargetRange(1,0)
    e1:SetTarget(cm.splimit)
    Duel.RegisterEffect(e1,tp)
end
function cm.splimit(e,c,sump,sumtype,sumpos,targetp,se)
    return c:GetRace()~=RACE_MACHINE
end
function cm.drtg2(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return Duel.IsPlayerCanDraw(tp,3) end
    Duel.SetTargetPlayer(tp)
    Duel.SetTargetParam(3)
    Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,tp,3)
end
function cm.drop2(e,tp,eg,ep,ev,re,r,rp)
    local p,d=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER,CHAININFO_TARGET_PARAM)
    Duel.Draw(p,d,REASON_EFFECT)
    local e1=Effect.CreateEffect(e:GetHandler())
    e1:SetType(EFFECT_TYPE_FIELD)
    e1:SetCode(EFFECT_CANNOT_BP)
    e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_OATH)
    e1:SetTargetRange(1,0)
    e1:SetReset(RESET_PHASE+PHASE_END)
    Duel.RegisterEffect(e1,tp)
end
function cm.drtg3(e,tp,eg,ep,ev,re,r,rp,chk)
    if chk==0 then return Duel.IsPlayerCanDraw(tp) end
    local ht=Duel.GetFieldGroupCount(tp,LOCATION_HAND,0)
    Duel.SetTargetPlayer(tp)
    Duel.SetTargetParam(5-ht)
    Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,tp,5-ht)
end
function cm.drop3(e,tp,eg,ep,ev,re,r,rp)
    local p=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER)
    local ht=Duel.GetFieldGroupCount(p,LOCATION_HAND,0)
    if ht<5 then
        Duel.Draw(p,5-ht,REASON_EFFECT)
    end
    local e1=Effect.CreateEffect(e:GetHandler())
    e1:SetType(EFFECT_TYPE_FIELD)
    e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_OATH)
    e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
    e1:SetReset(RESET_PHASE+PHASE_END)
    e1:SetTargetRange(1,0)
    e1:SetLabelObject(e)
    e1:SetTarget(cm.sumlimit2)
    Duel.RegisterEffect(e1,tp)
    local e2=Effect.CreateEffect(e:GetHandler())
    e2:SetType(EFFECT_TYPE_FIELD)
    e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_OATH)
    e2:SetCode(EFFECT_CANNOT_SUMMON)
    e2:SetReset(RESET_PHASE+PHASE_END)
    e2:SetTargetRange(1,0)
    Duel.RegisterEffect(e2,tp)
    local e3=Effect.CreateEffect(e:GetHandler())
    e3:SetType(EFFECT_TYPE_FIELD)
    e3:SetCode(EFFECT_CANNOT_ACTIVATE)
    e3:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_OATH)
    e3:SetReset(RESET_PHASE+PHASE_END)
    e3:SetValue(1)
    e3:SetTargetRange(1,0)
    Duel.RegisterEffect(e3,tp)
    local e4=Effect.CreateEffect(e:GetHandler())
    e4:SetType(EFFECT_TYPE_FIELD)
    e4:SetCode(EFFECT_CANNOT_ATTACK_ANNOUNCE)
    e4:SetProperty(EFFECT_FLAG_OATH)
    e4:SetTargetRange(LOCATION_MZONE,0)
    e4:SetReset(RESET_PHASE+PHASE_END)
    Duel.RegisterEffect(e4,tp)
end
function cm.sumlimit2(e,c,sump,sumtype,sumpos,targetp,se)
    return e:GetLabelObject()~=se
end